GET http://localhost:3000


###
GET http://localhost:3000/user/header

###
GET http://localhost:3000/common


###
GET http://localhost:3000/other

###
GET http://localhost:3000/config

###
GET http://localhost:3000/middle

###
GET http://localhost:3000/user/req

###
GET http://localhost:3000/user/query