GET http://localhost:3000


###
GET http://localhost:3000/user/header

###
GET http://localhost:3000/common


###
GET http://localhost:3000/other

###
GET http://localhost:3000/config

###
GET http://localhost:3000/middle

###
GET http://localhost:3000/user/req

###
GET http://localhost:3000/user/query

###
GET http://localhost:3000/exception


###
GET http://localhost:3000/forbiddenException

### 测试自定义控制器异常捕获
GET http://localhost:3000/customException1

### 测试自定义方法异常捕获 注册的是实例
GET http://localhost:3000/customException2

### 测试自定义方法异常捕获  注册的是类
GET http://localhost:3000/customException3

### 测试自定义控制器异常捕获
GET http://localhost:3000/customException4

### 测试自定义控制器异常捕获,作为provider使用
GET http://localhost:3000/customException5

### 测试管道 parseIntPipe 成功
GET http://localhost:3000/pipeInt/111

### 测试管道 parseIntPipe 失败
GET http://localhost:3000/pipeInt/aaa


### 测试管道 pipeArray
GET http://localhost:3000/pipeArray/1@2@3

### 测试管道 class-validate 和 class-transform
### 测试参数管道
POST http://localhost:3000/paramPipe/create
content-type: application/json

{
  "name": "jack",
  "age": "18"
}

### 测试参数管道
POST http://localhost:3000/methodPipe/create
content-type: application/json

{
  "name": "jack",
  "age": "18"
}

### 测试参数管道
POST http://localhost:3000/controllerPipe/create
content-type: application/json

{
  "name": "jack",
  "age": 18
}

### 测试参数管道
POST http://localhost:3000/globalPipe/create
content-type: application/json

{
  "name": "jack",
  "age": "18"
}

### 测试参数管道依赖注入
POST http://localhost:3000/globalPipeInject/create
content-type: application/json

{
  "name": "jack",
  "age": 18
}

### 测试守卫 有权限
GET http://localhost:3000/account?role=admin

### 测试守卫 没有权限
GET http://localhost:3000/account?role=user

### 测试守卫2
GET http://localhost:3000/account/role2?role=admin

### 测试全局守卫
GET http://localhost:3000/account/global?role=admin

### 测试拦截器
GET http://localhost:3000/pay

### 测试拦截器 转化数据
GET http://localhost:3000/pay/data

### 测试拦截器 错误捕获
GET http://localhost:3000/pay/error

### 测试拦截器 缓存捕获 发两次可以看到效果
GET http://localhost:3000/pay/cache?id=1

### 测试拦截器 请求超时
GET http://localhost:3000/pay/timeout

### 测试文件上传
POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.jpg"
Content-Type: image/jpg

< ./images/1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--